# Generated by Django 3.0.8 on 2020-07-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('author', models.TextField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('likes', models.TextField(blank=True, max_length=10)),
            ],
        ),
    ]
