# Generated by Django 3.0.8 on 2020-07-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='likes',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
